language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t iwasakiryota/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true iwasakiryota/react-test npm test

after_success:
  - docker build -t iwasakiryota/multi-client ./client
  - docker build -t iwasakiryota/multi-nginx ./nginx
  - docker build -t iwasakiryota/multi-server ./server
  - docker build -t iwasakiryota/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push iwasakiryota/multi-client
  - docker push iwasakiryota/multi-nginx
  - docker push iwasakiryota/multi-server
  - docker push iwasakiryota/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  resion: ap-northeast-1
  app: multi-docker
  env: MultiDocker-env1
  bucket_name: elasticbeanstalk-ap-northeast-1-078139916226
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
